use std::fmt::Write as _;

use oxc::allocator::Allocator;
use oxc::span::Span;

use crate::ir::{Module, NONE, TemplateId, UnitId};

/// The unit that first serialised each template row, indexed by [`TemplateId`].
///
/// P7 hands two units the same id when their bytes match, and a source map is a
/// FUNCTION from a generated position to a source position — one generated byte
/// cannot name two source sites, so "map every site" is not expressible and the
/// choice is between one site and none. It is the claimant: the bytes in
/// `Module::html` are literally its serialisation, and every other site stays
/// reachable through its own `_tmpl$N()` clone call, which carries that site's
/// own span on the ordinary AST path. Mapping to nobody would leave the template
/// unattributed for every site including the one that produced it.
pub fn claimants(module: &Module<'_>) -> Vec<UnitId> {
    let mut claimant = vec![NONE; module.templates.len()];
    for (index, unit) in module.units.iter().enumerate() {
        if unit.template == NONE {
            continue;
        }
        let slot = &mut claimant[unit.template as usize];
        if *slot == NONE {
            *slot = index as UnitId;
        }
    }
    claimant
}

/// The root JSX element a template row was built from, for the hoisted
/// `const _tmpl$N = …` declaration. Without it the declaration maps to the
/// enclosing `return (` — where the unit sat, not what it is.
pub fn template_span(module: &Module<'_>, claimant: &[UnitId], id: TemplateId) -> Option<Span> {
    let unit = module.units.get(*claimant.get(id as usize)? as usize)?;
    unit.spans.get(unit.skeleton.roots.0 as usize).copied().filter(|span| !span.is_empty())
}

/// One segment per `Skeleton::origin` entry, addressed into the INTERIOR
/// of the hoisted template literal, so a debugger stepping into `_tmpl$1` lands
/// on the JSX element whose markup those bytes are.
///
/// Runs after `Codegen::build`, because that is the first moment a generated
/// byte offset exists at all.
pub fn collect(module: &mut Module<'_>, code: &str) {
    if module.templates.is_empty() {
        return;
    }
    let claimant = claimants(module);
    let prefix = module.uids.template_prefix();
    let Module { units, templates, maps, html, .. } = module;

    let mut escaped = String::new();
    let mut name = String::new();
    let mut cursor = 0usize;

    for id in 0..templates.len() {
        let owner = claimant[id];
        if owner == NONE {
            continue;
        }
        let unit = &units[owner as usize];
        let row = &templates[id];
        let raw = &html[row.range.0 as usize..row.range.1 as usize];

        // Almost no template needs escaping, and rebuilding one that does not
        // is a copy of the whole html per template on the sourcemap path.
        let literal = if (0..raw.len()).any(|at| escape_width(raw.as_bytes(), at) > 0) {
            escaped.clear();
            escape_into(raw, &mut escaped);
            escaped.as_str()
        } else {
            raw
        };
        name.clear();
        name.push_str(prefix);
        let _ = write!(name, "{}", id + 1);

        let Some(start) = locate(code, cursor, &name, literal) else { continue };
        cursor = start + literal.len();
        maps.literals.push((start as u32, cursor as u32));

        let bytes = raw.as_bytes();
        let mut inserted = 0u32;
        let mut scanned = 0usize;
        for &(offset, span) in unit.skeleton.origin.iter() {
            let offset = offset as usize;
            while scanned < offset {
                inserted += escape_width(bytes, scanned);
                scanned += 1;
            }
            if span.is_empty() {
                continue;
            }
            maps.push_shadowing((start + offset) as u32 + inserted, span.start, NONE);
        }
    }
}

/// The byte offset just past the opening backtick of `const <name> = …`.
///
/// The prefix is absent from the source text, so no user identifier can carry
/// it — but a string literal reaching the output through re-escaping could, so
/// the html bytes themselves are the confirmation. A candidate that does not
/// carry them is skipped rather than mapped, because a wrong segment is worse
/// than a missing one.
fn locate(code: &str, from: usize, name: &str, escaped: &str) -> Option<usize> {
    /// `" = /* @__PURE__ */ _$template("` and any `$` padding hygiene added.
    const CALL_PREFIX_LIMIT: usize = 128;

    for base in [from, 0] {
        let mut at = base;
        while let Some(found) = code.get(at..).and_then(|rest| rest.find(name)).map(|it| it + at) {
            at = found + name.len();
            let Some(after) = code.get(at..).and_then(|rest| rest.strip_prefix(" = ")) else {
                continue;
            };
            // Bytes, not a `str` slice: the limit is a budget, not a boundary,
            // and the html a template carries is arbitrary UTF-8, so a slice at
            // a fixed byte count lands inside a character whenever one straddles
            // it. A backtick is ASCII, so searching the bytes is exact.
            let limit = after.len().min(CALL_PREFIX_LIMIT);
            let Some(tick) = after.as_bytes()[..limit].iter().position(|byte| *byte == b'`') else {
                continue;
            };
            let start = at + 3 + tick + 1;
            if code[start..].starts_with(escaped) {
                return Some(start);
            }
        }
        if from == 0 {
            break;
        }
    }
    None
}

/// The bytes a template literal in the OUTPUT carries for a run of template
/// html. Borrows when nothing needs escaping, which is almost every template.
///
/// This is what both backends emit through, so it is also what the offset
/// arithmetic in `escape_width` reproduces: a segment placed at the unescaped
/// offset would drift by one per escape.
pub(super) fn template_raw<'a>(raw: &'a str, allocator: &'a Allocator) -> &'a str {
    // Deliberately looser than `escape_width`: a lone `$` takes the copying path
    // and `escape_into` then leaves it alone, so the bytes are the same either
    // way, and a membership test over four bytes is one the autovectoriser can
    // widen where a per-index call with a lookahead is not.
    if !raw.as_bytes().iter().any(|byte| matches!(byte, b'\\' | b'`' | b'\r' | b'$')) {
        return raw;
    }
    let mut out = String::with_capacity(raw.len() + 8);
    escape_into(raw, &mut out);
    allocator.alloc_str(&out)
}

/// `TemplateElement::new_escape_raw`, reproduced.
///
/// U+2028 and U+2029 are deliberately NOT escaped: a JS engine treats them as
/// line terminators, so a template that bakes one really does start a new
/// generated line, and `LineIndex` is what models that on both sides of the
/// map.
fn escape_into(raw: &str, out: &mut String) {
    out.reserve(raw.len());
    let bytes = raw.as_bytes();
    for (at, ch) in raw.char_indices() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '`' => out.push_str("\\`"),
            '\r' => out.push_str("\\r"),
            '$' if bytes.get(at + 1) == Some(&b'{') => out.push_str("\\$"),
            _ => out.push(ch),
        }
    }
}

fn escape_width(bytes: &[u8], at: usize) -> u32 {
    match bytes[at] {
        b'\\' | b'`' | b'\r' => 1,
        b'$' if bytes.get(at + 1) == Some(&b'{') => 1,
        _ => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_escape_matches_the_one_the_ast_builder_applies() {
        let mut out = String::new();
        escape_into("a`b\\c${d}e", &mut out);
        assert_eq!(out, "a\\`b\\\\c\\${d}e");

        // A lone `$` is not escaped, so it must not shift anything either.
        let mut out = String::new();
        escape_into("a$b", &mut out);
        assert_eq!(out, "a$b");
        assert_eq!(escape_width(b"a$b", 1), 0);
        assert_eq!(escape_width(b"a${", 1), 1);

        // A JS line terminator stays raw: `LineIndex` counts it as ending a
        // generated line, which is what a JS engine does with it.
        let mut out = String::new();
        escape_into("a\u{2028}b", &mut out);
        assert_eq!(out, "a\u{2028}b");
        assert_eq!(escape_width("\u{2028}".as_bytes(), 0), 0);
    }

    #[test]
    fn a_candidate_that_does_not_carry_the_html_is_refused() {
        let code = "const s = \"_tmpl$1 = `<b>x</b>`\";\nconst _tmpl$1 = _$template(`<i>y</i>`);";
        // The decoy is a string whose bytes are not this template's html.
        assert_eq!(locate(code, 0, "_tmpl$1", "<i>y</i>"), code.find("<i>y</i>"));
        // Nothing in the module carries these bytes, so nothing is mapped.
        assert_eq!(locate(code, 0, "_tmpl$1", "<u>z</u>"), None);
    }

    #[test]
    fn a_multibyte_character_at_the_search_limit_is_never_sliced_in_half() {
        // `_$template(` + the backtick is 28 bytes, so the 128-byte call-prefix
        // budget lands on byte 100 of the html: an ordinary accented word in an
        // ordinary paragraph puts a two-byte character across it.
        for pad in 80..120 {
            let html = format!("<p class=\"lead\">{}é b</p>", "a".repeat(pad));
            let code = format!("const _tmpl$1 = /* @__PURE__ */ _$template(`{html}`);");
            assert_eq!(locate(&code, 0, "_tmpl$1", &html), Some(code.find('`').unwrap() + 1));
        }
    }

    #[test]
    fn the_search_restarts_from_the_top_when_the_cursor_has_passed_it() {
        let code = "const _tmpl$1 = _$template(`<i>y</i>`);\n";
        assert!(locate(code, code.len(), "_tmpl$1", "<i>y</i>").is_some());
    }
}
