/**
 * `@barqjs/aria` — accessible interactions, state and headless components.
 *
 * Every module is an entry point of its own as well as being re-exported here,
 * so `@barqjs/aria/listbox` and a tree-shaken import from the root cost the
 * same. The re-exports are named rather than `export *`: a name defined in two
 * modules is silently dropped from a star export, and this package has enough
 * surface for that to happen without anyone noticing.
 *
 * Two things separate it from `react-aria`, which it was studied from:
 *
 * - **Names carry no `use` prefix.** A component here runs once and there is no
 *   rules-of-hooks to signal, so `press()`, `button()` and `listBox()` are what
 *   they are called.
 * - **Collections are data-driven.** `items` plus a render function, rather
 *   than a first pass that renders the children to find out what they declare.
 *   See `collections.ts`.
 */

// -------------------------------------------------------------------------
// The platform, the DOM and the values every hook takes
// -------------------------------------------------------------------------

export {
  isAndroid,
  isAppleDevice,
  isChrome,
  isFirefox,
  isIOS,
  isIPad,
  isIPhone,
  isMac,
  isSafari,
  isWebKit,
} from "./platform.ts";
export {
  activeElement,
  addEvent,
  contains,
  enableShadowDOM,
  eventTarget,
  focusWithoutScrolling,
  isDocument,
  isElementVisible,
  isFocusable,
  isNode,
  isScrollable,
  isShadowDOMEnabled,
  isShadowRoot,
  isTabbable,
  ownerDocument,
  ownerWindow,
  PREVENT_FOCUS_ATTRIBUTE,
  propagationTargets,
  runAfterTransition,
  scrollIntoView,
  type ScrollIntoViewOptions,
  scrollIntoViewport,
  scrollParents,
  setStyle,
  targetElement,
  TOP_LAYER_ATTRIBUTE,
} from "./dom.ts";
export {
  access,
  callback,
  chain,
  clamp,
  type Controllable,
  controllable,
  type DOMProps,
  filterDOMProps,
  type FilterDOMPropsOptions,
  fromProps,
  id,
  labelProps,
  type MaybeAccessor,
  mergeIds,
  mergeProps,
  type Options,
  provideTriggerSlot,
  roundToStepPrecision,
  snapValueToStep,
  type GlobalEvents,
  type StyleProps,
  styleProps,
  toFixedNumber,
  type TriggerSlot,
  triggerSlot,
} from "./utils.ts";
export {
  collator,
  dateFormatter,
  defaultLocale,
  type Filter,
  filter,
  isRTL,
  listFormatter,
  type Locale,
  LocaleContext,
  type LocalizedString,
  type LocalizedStrings,
  numberFormatter,
  NumberParser,
  numberParser,
  provideLocale,
  StringDictionary,
  StringFormatter,
  stringFormatter,
  useLocale,
  type Variables,
} from "./i18n.ts";
export {
  announce,
  type Announcement,
  type Assertiveness,
  clearAnnouncer,
  destroyAnnouncer,
  visuallyHidden,
  type VisuallyHiddenOptions,
  type VisuallyHiddenResult,
} from "./live.ts";
export {
  field,
  type FieldId,
  type FieldOptions,
  type FieldResult,
  label,
  type LabelOptions,
  type LabelResult,
} from "./label.ts";

// -------------------------------------------------------------------------
// What the user did
// -------------------------------------------------------------------------

export {
  type BaseEvent,
  createEventHandler,
  description,
  disableTextSelection,
  type ElementRef,
  focusable,
  type FocusableOptions,
  type FocusableResult,
  focused,
  type FocusOptions,
  type FocusResult,
  focusSafely,
  focusVisible,
  focusWithin,
  type FocusWithinOptions,
  type FocusWithinResult,
  getInteractionModality,
  getPointerType,
  type GlobalListeners,
  globalListeners,
  handleLinkClick,
  hover,
  type HoverEvent,
  type HoverOptions,
  type HoverResult,
  interactOutside,
  type InteractOutsideOptions,
  isFocusVisible,
  isVirtualClick,
  isVirtualPointerEvent,
  keyboard,
  type KeyboardOptions,
  type KeyboardResult,
  type LinkModifiers,
  longPress,
  type LongPressEvent,
  type LongPressOptions,
  type LongPressResult,
  type Modality,
  modality,
  type ModalityHandler,
  move,
  type MoveEndEvent,
  type MoveMoveEvent,
  type MoveOptions,
  type MoveResult,
  type MoveStartEvent,
  onModalityChange,
  openLink,
  type PointerType,
  press,
  type PressEvent,
  type PressOptions,
  type PressResult,
  preventFocus,
  restoreTextSelection,
  type Router,
  router,
  RouterContext,
  scrollWheel,
  type ScrollWheelOptions,
  setInteractionModality,
  shouldClientNavigate,
  syntheticLinkProps,
  trackModality,
  untrackModality,
} from "./interactions.ts";
export {
  createFocusManager,
  focusableWalker,
  type FocusManager,
  focusManager,
  focusRing,
  type FocusRingOptions,
  type FocusRingResult,
  focusScope,
  FocusScopeContext,
  type FocusScopeOptions,
  type FocusScopeResult,
  FocusWalker,
  type FocusWalkerOptions,
} from "./focus.ts";

// -------------------------------------------------------------------------
// Collections, selection and the state a component keeps
// -------------------------------------------------------------------------

export {
  buildCollection,
  type Collection,
  type DisabledBehavior,
  type FocusStrategy,
  type ItemAccessors,
  type Key,
  type LayoutDelegate,
  ListCollection,
  type ListState,
  listState,
  type ListStateOptions,
  type MultipleSelectionOptions,
  type MultipleSelectionState,
  multipleSelectionState,
  type Node,
  type Rect,
  Selection,
  type SelectionBehavior,
  SelectionManager,
  type SelectionMode,
  type SelectionValue,
  type SingleSelectListOptions,
  type SingleSelectListState,
  singleSelectListState,
  type Size,
} from "./collections.ts";
export {
  type Direction,
  DOMLayoutDelegate,
  isCtrlKeyPressed,
  isNonContiguousSelectionModifier,
  itemElement,
  type KeyboardDelegate,
  type LinkBehavior,
  ListKeyboardDelegate,
  type ListKeyboardDelegateOptions,
  type Orientation,
  selectableCollection,
  type SelectableCollectionOptions,
  type SelectableCollectionResult,
  selectableItem,
  type SelectableItemOptions,
  type SelectableItemResult,
  selectableList,
  type SelectableListOptions,
  typeSelect,
  type TypeSelectOptions,
  type TypeSelectResult,
} from "./selection.ts";
export {
  type AnchorRect,
  ariaHideOutside,
  type Axis,
  closeOnScroll,
  dismissButtonProps,
  keepVisible,
  modalOverlay,
  type ModalOverlayOptions,
  type ModalOverlayResult,
  overlay,
  type OverlayOptions,
  overlayPosition,
  type OverlayResult,
  overlayTrigger,
  type OverlayTriggerOptions,
  type OverlayTriggerResult,
  type OverlayTriggerState,
  overlayTriggerState,
  type OverlayTriggerStateOptions,
  type Placement,
  portalContainer,
  type PortalTarget,
  type PositionOptions,
  type PositionResult,
  preventScroll,
  providePortalTarget,
  topLayerProps,
  usePortalTarget,
} from "./overlays.ts";
export { exitDuration, presence, type PresenceOptions, type PresenceResult } from "./presence.ts";
export {
  type FieldValidation,
  fieldValidation,
  type FieldValidationOptions,
  formValidation,
  type FormValidationOptions,
  type FormValidationState,
  formValidationState,
  type FormValidationStateOptions,
  nativeValidity,
  provideValidationBehavior,
  provideValidationErrors,
  useValidationBehavior,
  VALID_RESULT,
  type ValidatableElement,
  type ValidateFunction,
  type ValidationBehavior,
  type ValidationErrors,
  type ValidationResult,
} from "./validation.ts";
export {
  CalendarDate,
  CalendarDateTime,
  constrainDate,
  type DateTimeUnit,
  type DateUnit,
  type DateValue,
  endOfMonth,
  endOfWeek,
  endOfYear,
  getDayOfWeek,
  getDaysInMonth,
  getFirstDayOfWeek,
  getWeekendDays,
  getWeeksInMonth,
  isDateUnavailable,
  isLeapYear,
  isSameDay,
  isSameMonth,
  isToday,
  isWeekend,
  now,
  parseDate,
  parseDateTime,
  parseTime,
  startOfMonth,
  startOfWeek,
  startOfYear,
  Time,
  type TimeUnit,
  toCalendarDate,
  today,
} from "./date.ts";
export {
  Color,
  type ColorChannel,
  type ColorChannelRange,
  type ColorFormat,
  type ColorSpace,
  defaultColor,
  HSBColor,
  HSLColor,
  parseColor,
  RGBColor,
} from "./color.ts";

// -------------------------------------------------------------------------
// Components
// -------------------------------------------------------------------------

export {
  Breadcrumb,
  type BreadcrumbComponentProps,
  breadcrumbItem,
  type BreadcrumbItemOptions,
  type BreadcrumbItemResult,
  Breadcrumbs,
  breadcrumbs,
  type BreadcrumbsComponentProps,
  type BreadcrumbsOptions,
  type BreadcrumbsResult,
  useBreadcrumbs,
  useCrumb,
} from "./breadcrumbs.tsx";
export {
  Button,
  button,
  type ButtonComponentProps,
  type ButtonOptions,
  type ButtonResult,
  ToggleButton,
  toggleButton,
  type ToggleButtonComponentProps,
  type ToggleButtonOptions,
  type ToggleButtonResult,
  type ToggleState,
  toggleState,
  type ToggleStateOptions,
} from "./button.tsx";
export {
  Calendar,
  calendar,
  CalendarCell,
  calendarCell,
  type CalendarCellComponentProps,
  type CalendarCellOptions,
  type CalendarCellResult,
  type CalendarComponentProps,
  calendarGrid,
  type CalendarGridOptions,
  type CalendarGridResult,
  type CalendarOptions,
  type CalendarResult,
  type CalendarState,
  calendarState,
  type CalendarStateOptions,
  type DateRange,
  RangeCalendar,
  type RangeCalendarComponentProps,
  type RangeCalendarState,
  rangeCalendarState,
  type RangeCalendarStateOptions,
  useCalendar,
} from "./calendar.tsx";
export {
  Checkbox,
  checkbox,
  type CheckboxComponentProps,
  CheckboxGroup,
  checkboxGroup,
  type CheckboxGroupComponentProps,
  type CheckboxGroupOptions,
  type CheckboxGroupResult,
  type CheckboxGroupState,
  checkboxGroupState,
  type CheckboxGroupStateOptions,
  type CheckboxOptions,
  type CheckboxResult,
  GroupCheckbox,
  type GroupCheckboxProps,
  useCheckboxGroup,
} from "./checkbox.tsx";
export {
  ColorArea,
  colorArea,
  type ColorAreaComponentProps,
  type ColorAreaOptions,
  type ColorAreaResult,
  type ColorAreaState,
  colorAreaState,
  type ColorAreaStateOptions,
  ColorField,
  colorField,
  type ColorFieldComponentProps,
  type ColorFieldOptions,
  type ColorFieldResult,
  ColorPicker,
  type ColorPickerComponentProps,
  ColorSlider,
  colorSlider,
  type ColorSliderComponentProps,
  type ColorSliderOptions,
  type ColorSliderResult,
  type ColorSliderState,
  colorSliderState,
  type ColorSliderStateOptions,
  type ColorStateOptions,
  ColorSwatch,
  colorSwatch,
  type ColorSwatchComponentProps,
  type ColorSwatchOptions,
  type ColorSwatchResult,
  ColorWheel,
  colorWheel,
  type ColorWheelComponentProps,
  type ColorWheelOptions,
  type ColorWheelResult,
  type ColorWheelState,
  colorWheelState,
  type ColorWheelStateOptions,
  useColorPicker,
} from "./colorpicker.tsx";
export {
  ComboBox,
  comboBox,
  type ComboBoxComponentProps,
  type ComboBoxOptions,
  type ComboBoxResult,
  type ComboBoxState,
  comboBoxState,
  type ComboBoxStateOptions,
  type FilterFn,
  type MenuTriggerAction,
  useComboBox,
} from "./combobox.tsx";
export {
  DateField,
  dateField,
  type DateFieldComponentProps,
  type DateFieldOptions,
  type DateFieldResult,
  type DateFieldState,
  dateFieldState,
  type DateFieldStateOptions,
  type DateSegment,
  dateSegment,
  type DateSegmentOptions,
  type DateSegmentResult,
  type Granularity,
  type SegmentType,
  TimeField,
  type TimeFieldComponentProps,
  useDateField,
} from "./datefield.tsx";
export {
  DatePicker,
  datePicker,
  type DatePickerComponentProps,
  type DatePickerOptions,
  type DatePickerResult,
  type DatePickerState,
  datePickerState,
  type DatePickerStateOptions,
  DateRangePicker,
  type DateRangePickerComponentProps,
  useDatePicker,
} from "./datepicker.tsx";
export {
  Dialog,
  dialog,
  type DialogComponentProps,
  type DialogOptions,
  type DialogResult,
  type DialogState,
  DialogTrigger,
  type DialogTriggerComponentProps,
  type DialogTriggerValue,
  Heading,
  type HeadingComponentProps,
  Modal,
  type ModalComponentProps,
  Popover,
  type PopoverComponentProps,
  PortalProvider,
  type PortalProviderComponentProps,
  useDialogTitle,
  useDialogTrigger,
  usePopoverGroup,
} from "./dialog.tsx";
export {
  Disclosure,
  disclosure,
  DisclosureButton,
  type DisclosureButtonComponentProps,
  type DisclosureComponentProps,
  DisclosureGroup,
  type DisclosureGroupComponentProps,
  DisclosureGroupItem,
  type DisclosureGroupItemComponentProps,
  type DisclosureGroupState,
  disclosureGroupState,
  type DisclosureGroupStateOptions,
  type DisclosureOptions,
  DisclosurePanel,
  type DisclosurePanelComponentProps,
  type DisclosureResult,
  type DisclosureState,
  disclosureState,
  type DisclosureStateOptions,
  useDisclosure,
  useDisclosureGroup,
  useDisclosureNode,
} from "./disclosure.tsx";
export { Form, type FormComponentProps } from "./form.tsx";
export {
  GridList,
  gridList,
  type GridListComponentProps,
  GridListItem,
  gridListItem,
  type GridListItemComponentProps,
  type GridListItemOptions,
  type GridListItemResult,
  type GridListOptions,
  GridListProvider,
  type GridListResult,
  type KeyboardNavigationBehavior,
  provideRowNode,
  rowIdFor,
  useGridList,
  useRowNode,
} from "./gridlist.tsx";
export {
  Link,
  link,
  type LinkComponentProps,
  type LinkOptions,
  type LinkResult,
  Meter,
  meter,
  type MeterComponentProps,
  ProgressBar,
  progressBar,
  type ProgressBarComponentProps,
  type ProgressBarOptions,
  type ProgressBarResult,
  Separator,
  separator,
  type SeparatorComponentProps,
  type SeparatorOptions,
} from "./link.tsx";
export {
  ListBox,
  listBox,
  type ListBoxComponentProps,
  type ListBoxContextValue,
  type ListBoxOptions,
  ListBoxProvider,
  type ListBoxResult,
  listBoxSection,
  type ListBoxSectionOptions,
  Option,
  option,
  type OptionComponentProps,
  optionIdFor,
  type OptionOptions,
  type OptionResult,
  provideItemNode,
  useItemNode,
  useListBox,
} from "./listbox.tsx";
export {
  ContextMenu,
  type ContextMenuComponentProps,
  ContextMenuTrigger,
  type ContextMenuTriggerComponentProps,
  contextMenuTrigger,
  type ContextMenuTriggerOptions,
  type ContextMenuTriggerResult,
  Menu,
  menu,
  MenuButton,
  type MenuButtonComponentProps,
  type MenuComponentProps,
  MenuItem,
  menuItem,
  type MenuItemComponentProps,
  menuItemIdFor,
  type MenuItemOptions,
  type MenuItemResult,
  type MenuOptions,
  type MenuResult,
  MenuSection,
  menuSection,
  type MenuSectionComponentProps,
  type MenuSectionOptions,
  type MenuSectionResult,
  MenuTrigger,
  menuTrigger,
  type MenuTriggerComponentProps,
  type MenuTriggerOptions,
  type MenuTriggerResult,
  type MenuTriggerState,
  menuTriggerState,
  type MenuTriggerStateOptions,
  type MenuTriggerType,
  type MenuTriggerValue,
  provideMenuNode,
  type RootMenuTriggerState,
  safelyMouseToSubmenu,
  type SafelyMouseToSubmenuOptions,
  SubmenuTrigger,
  submenuTrigger,
  type SubmenuTriggerComponentProps,
  type SubmenuTriggerOptions,
  type SubmenuTriggerResult,
  type SubmenuTriggerState,
  submenuTriggerState,
  type SubmenuTriggerStateOptions,
  type SubmenuTriggerValue,
  useMenu,
  useMenuNode,
  useMenuTrigger,
  useSubmenuTrigger,
} from "./menu.tsx";
export {
  NumberField,
  numberField,
  type NumberFieldComponentProps,
  type NumberFieldOptions,
  type NumberFieldResult,
  type NumberFieldState,
  numberFieldState,
  type NumberFieldStateOptions,
  spinButton,
  type SpinButtonOptions,
  type SpinButtonResult,
  useNumberField,
} from "./numberfield.tsx";
export {
  Radio,
  radio,
  type RadioComponentProps,
  RadioGroup,
  radioGroup,
  type RadioGroupComponentProps,
  type RadioGroupOptions,
  type RadioGroupResult,
  type RadioGroupState,
  radioGroupState,
  type RadioGroupStateOptions,
  type RadioOptions,
  type RadioResult,
  useRadioGroup,
} from "./radio.tsx";
export {
  hiddenSelect,
  type HiddenSelectOptions,
  type HiddenSelectResult,
  Select,
  select,
  type SelectComponentProps,
  type SelectOptions,
  type SelectResult,
  type SelectState,
  selectState,
  type SelectStateOptions,
  SelectValue,
  type SelectValueComponentProps,
  useSelect,
} from "./select.tsx";
export {
  Slider,
  slider,
  type SliderComponentProps,
  type SliderContextValue,
  type SliderOptions,
  SliderOutput,
  type SliderOutputComponentProps,
  type SliderResult,
  type SliderState,
  sliderState,
  type SliderStateOptions,
  SliderThumb,
  sliderThumb,
  type SliderThumbComponentProps,
  type SliderThumbOptions,
  type SliderThumbResult,
  SliderTrack,
  type SliderTrackComponentProps,
  useSlider,
} from "./slider.tsx";
export {
  Switch,
  type SwitchComponentProps,
  type SwitchOptions,
  type SwitchResult,
  switchToggle,
} from "./switch.tsx";
export {
  Cell,
  type CellComponentProps,
  cellIdFor,
  cellKeyFor,
  Column,
  type ColumnComponentProps,
  columnHeaderIdFor,
  Row,
  type RowComponentProps,
  type SortDescriptor,
  Table,
  table,
  TableBody,
  type TableBodyComponentProps,
  tableCell,
  type TableCellOptions,
  type TableCellResult,
  TableCollection,
  tableColumnHeader,
  type TableColumnHeaderOptions,
  type TableColumnHeaderResult,
  type TableColumnProps,
  type TableComponentProps,
  TableHeader,
  type TableHeaderComponentProps,
  TableKeyboardDelegate,
  type TableKeyboardDelegateOptions,
  type TableOptions,
  type TableResult,
  tableRow,
  type TableRowOptions,
  type TableRowResult,
  type TableState,
  tableState,
  type TableStateOptions,
  useColumn,
  useRow,
  useTable,
} from "./table.tsx";
export {
  Tab,
  tab,
  type TabComponentProps,
  TabList,
  tabList,
  type TabListComponentProps,
  type TabListOptions,
  type TabListResult,
  type TabListState,
  tabListState,
  type TabListStateOptions,
  type TabOptions,
  TabPanel,
  tabPanel,
  type TabPanelComponentProps,
  type TabPanelOptions,
  type TabPanelResult,
  type TabResult,
  Tabs,
  type TabsComponentProps,
  TabsKeyboardDelegate,
  type TabsKeyboardDelegateOptions,
  useTabNode,
  useTabs,
} from "./tabs.tsx";

export {
  toastQueue,
  type Toast,
  type ToastKind,
  type ToastOptions,
  type ToastQueue,
  type ToastQueueOptions,
} from "./toast.ts";

export {
  navigationMenuState,
  type MotionDirection,
  type NavigationMenuState,
  type NavigationMenuStateOptions,
} from "./navigation.ts";
export {
  Tag,
  tag,
  type TagComponentProps,
  TagGroup,
  tagGroup,
  type TagGroupComponentProps,
  type TagGroupOptions,
  type TagGroupResult,
  tagIdFor,
  type TagOptions,
  type TagResult,
  useTagGroup,
  useTagNode,
} from "./tag.tsx";
export {
  SearchField,
  searchField,
  type SearchFieldComponentProps,
  type SearchFieldOptions,
  type SearchFieldResult,
  TextField,
  textField,
  type TextFieldComponentProps,
  type TextFieldOptions,
  type TextFieldResult,
  type TextFieldType,
} from "./textfield.tsx";
export {
  documentOf,
  formReset,
  HIDDEN_INPUT_STYLE,
  toggle,
  type ToggleOptions,
  type ToggleResult,
} from "./toggle.ts";
export {
  Toolbar,
  toolbar,
  type ToolbarComponentProps,
  type ToolbarOptions,
  type ToolbarResult,
} from "./toolbar.tsx";
export {
  resetTooltipWarmup,
  Tooltip,
  tooltip,
  type TooltipComponentProps,
  type TooltipOptions,
  type TooltipResult,
  TooltipTrigger,
  tooltipTrigger,
  type TooltipTriggerComponentProps,
  type TooltipTriggerOptions,
  type TooltipTriggerResult,
  type TooltipTriggerState,
  tooltipTriggerState,
  type TooltipTriggerStateOptions,
  type TooltipTriggerValue,
  useTooltipTrigger,
} from "./tooltip.tsx";
export {
  contentStyle,
  Layout,
  type LayoutContext,
  type LayoutInfo,
  layoutInfo,
  ListLayout,
  listLayout,
  type ListLayoutOptions,
  measureRow,
  type Point,
  rect,
  rectContainsPoint,
  rectEquals,
  rectIntersects,
  rectMaxX,
  rectMaxY,
  rowStyle,
  useVirtualizer,
  Virtualizer,
  virtualizer,
  type VirtualizerComponentProps,
  type VirtualizerOptions,
  type VirtualizerState,
  type VirtualizerValue,
} from "./virtualizer.tsx";
