/**
 * `src/index.ts` and the `exports` map, from what `src/ui` actually contains.
 *
 * ```
 * bun run exports
 * ```
 *
 * Three lists have to agree — the barrel, the package's `exports` and the build
 * entries — and keeping them by hand means a component that works from
 * `@barqjs/ui` and 404s from `@barqjs/ui/badge`. They are all derived from the
 * files instead.
 *
 * It parses the `export` keyword rather than typechecking: a declaration this
 * package writes is `export function`, `export const`, `export interface` or
 * `export type`, all at the top level, so a regex over line starts sees every
 * one of them. Anything cleverer would be a compiler.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");

interface Module {
  /** `button`, for `./ui/button.tsx` and `@barqjs/ui/button`. */
  readonly name: string;
  readonly file: string;
  readonly values: string[];
  readonly types: string[];
}

const DECLARATION =
  /^export (?:async )?(?:function|const|class|let|var)\s+([A-Za-z_$][\w$]*)|^export (?:interface|type)\s+([A-Za-z_$][\w$]*)/gm;

/** `export { A, type B } from "…"` — a module that re-exports what it wraps. */
const REEXPORT = /^export \{([^}]*)\}/gm;

function declarationsIn(source: string): { values: string[]; types: string[] } {
  const values: string[] = [];
  const types: string[] = [];

  for (const match of source.matchAll(DECLARATION)) {
    if (match[1] !== undefined) values.push(match[1]);
    else if (match[2] !== undefined) types.push(match[2]);
  }
  for (const match of source.matchAll(REEXPORT)) {
    for (const entry of (match[1] ?? "").split(",")) {
      const name = entry
        .trim()
        .replace(/^type\s+/, "")
        .split(/\s+as\s+/)
        .at(-1)
        ?.trim();
      if (name === undefined || name === "") continue;
      if (entry.trim().startsWith("type ")) types.push(name);
      else values.push(name);
    }
  }
  return { values: [...new Set(values)].toSorted(), types: [...new Set(types)].toSorted() };
}

function modulesIn(directory: string, prefix: string): Module[] {
  return readdirSync(join(root, "src", directory))
    .filter((entry) => /\.tsx?$/.test(entry) && !entry.includes(".test."))
    .toSorted()
    .map((entry) => {
      const source = readFileSync(join(root, "src", directory, entry), "utf8");
      return {
        name: entry.replace(/\.tsx?$/, ""),
        file: `./${prefix}${entry}`,
        ...declarationsIn(source),
      };
    })
    .filter((module_) => module_.values.length > 0 || module_.types.length > 0);
}

function block(module_: Module): string {
  const names = [...module_.values, ...module_.types.map((name) => `type ${name}`)].toSorted(
    (a, b) => a.replace("type ", "").localeCompare(b.replace("type ", "")),
  );
  const one = `export { ${names.join(", ")} } from "${module_.file}";`;
  if (one.length <= 100) return one;
  return `export {\n${names.map((name) => `  ${name},`).join("\n")}\n} from "${module_.file}";`;
}

const HEADER = `/**
 * \`@barqjs/ui\` — shadcn/ui's components, on \`@barqjs/aria\` and \`@barqjs/css\`.
 *
 * GENERATED by \`tools/exports.ts\` from what \`src/ui\` contains. Edit that, not
 * this.
 *
 * Importing this installs the scale and the layer order every component's CSS
 * reads. The RESET is a separate import (\`@barqjs/ui/theme/reset\`) and a colour
 * theme is chosen by you, because neither is a decision a component library
 * gets to make for an application.
 *
 * Every component is an entry point of its own as well as being re-exported
 * here, so \`@barqjs/ui/button\` and a tree-shaken import from the root cost the
 * same.
 */

import "./theme/base.ts";
`;

function main(): void {
  const ui = modulesIn("ui", "ui/");
  const lib = modulesIn("lib", "lib/");
  const theme: Module[] = [
    {
      name: "theme",
      file: "./theme/index.ts",
      ...declarationsIn(readFileSync(join(root, "src/theme/index.ts"), "utf8")),
    },
  ];

  writeFileSync(
    join(root, "src/index.ts"),
    [HEADER, ...[...lib, ...theme, ...ui].map(block), ""].join("\n"),
  );

  const packagePath = join(root, "package.json");
  const manifest = JSON.parse(readFileSync(packagePath, "utf8")) as {
    exports: Record<string, unknown>;
    sideEffects: unknown;
  };

  // Only the theme has one. Every component module registers its CSS at import
  // time, which IS a side effect — but a bundler only drops a module when
  // nothing it exports is used, and a component nobody imports has no CSS worth
  // keeping. The theme is different: it is imported for its effect alone, and
  // `sideEffects: false` would let a bundler drop the scale every component's
  // CSS reads.
  manifest.sideEffects = ["./dist/theme/*.js", "./src/theme/*.ts"];

  // SOURCE, under a `barq` condition, because no build can be right for every
  // consumer: the same file emits `template()`/`spread` for the DOM and
  // `html()`/`esc()` for a string render, and `hydratable` moves it again.
  // `@barqjs/compiler/vite` puts `barq` first in every environment and compiles
  // this package out of `node_modules`.
  const entry = (file: string): Record<string, string> => ({
    types: file,
    barq: file,
    bun: file,
  });

  manifest.exports = {
    ".": entry("./src/index.ts"),
    "./theme": entry("./src/theme/index.ts"),
    "./theme/reset": entry("./src/theme/reset.ts"),
    ...Object.fromEntries(
      [...lib, ...ui].map((module_) => [
        `./${module_.name}`,
        entry(`./src/${module_.file.slice(2)}`),
      ]),
    ),
    "./package.json": "./package.json",
  };

  writeFileSync(packagePath, `${JSON.stringify(manifest, null, 2)}\n`);

  writeFileSync(
    join(root, "src/entries.ts"),
    [
      "/**",
      " * Every module this package builds, for `tsdown.config.ts` and for the",
      " * registry.",
      " *",
      " * GENERATED by `tools/exports.ts`. Edit that, not this.",
      " */",
      "",
      `export const ENTRIES: readonly string[] = ${JSON.stringify(
        [
          "index.ts",
          "theme/index.ts",
          "theme/reset.ts",
          // Entries of their own so they stay MODULES. Rolled into a shared
          // chunk they get a hashed name, which `sideEffects` cannot match, and
          // a bundler then drops the scale every component's CSS reads.
          "theme/base.ts",
          "theme/layers.ts",
          ...[...lib, ...ui].map((module_) => module_.file.slice(2)),
        ],
        null,
        2,
      )};`,
      "",
    ].join("\n"),
  );

  process.stdout.write(
    `${ui.length} components, ${lib.length} library modules -> src/index.ts, exports, src/entries.ts\n`,
  );
}

main();
