/**
 * shadcn's eight styles, as eight stylesheets this package can serve.
 *
 * ```
 * bun run tools/styles.ts ../ui
 * ```
 *
 * Upstream publishes each style as one CSS file of semantic classes, every one
 * of them an `@apply` of a Tailwind class list:
 *
 *     .cn-button-variant-ghost { @apply hover:bg-muted hover:text-foreground; }
 *
 * Which is the same input `specs/*.json` holds and the same translation
 * `transcribe.ts` runs, so the whole of a style goes through `css.ts` unchanged.
 * What comes out is the file upstream would have shipped if it were not written
 * in Tailwind: ordinary nested CSS, in `@layer barq.ui`, scoped by the style's
 * own class so an application can hold more than one.
 *
 * A utility that resolves to nothing is REPORTED rather than dropped, because a
 * missing rule is invisible: the component simply loses part of its look.
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";

import { createBuilder, translate } from "./css.ts";

const LAYER = "barq.ui";

/** `.cn-slot { @apply … }` blocks, as slot to class list. */
export function parseStyle(source: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const [, slot, body] of source.matchAll(
    /^ {2}\.(cn-[a-z0-9-]+)\s*\{\s*([\s\S]*?)\s*\}\s*$/gm,
  )) {
    const applied = [...(body ?? "").matchAll(/@apply\s+([^;]+);/g)]
      .map((match) => (match[1] ?? "").split(/\s+/).filter(Boolean).join(" "))
      .join(" ")
      .trim();
    if (slot !== undefined && applied !== "") out.set(slot, applied);
  }
  return out;
}

function indent(text: string, by: string): string {
  return text
    .split("\n")
    .map((line) => (line === "" ? line : `${by}${line}`))
    .join("\n");
}

async function main(): Promise<void> {
  const checkout = process.argv[2] ?? "../ui";
  const from = resolve(process.cwd(), checkout, "apps/v4/registry/styles");
  const into = resolve(import.meta.dir, "../styles");
  mkdirSync(into, { recursive: true });

  const build = await createBuilder();
  let missing = 0;

  for (const file of readdirSync(from).toSorted()) {
    if (!file.startsWith("style-") || !file.endsWith(".css")) continue;
    const name = basename(file, ".css").replace(/^style-/, "");
    const slots = parseStyle(readFileSync(join(from, file), "utf8"));

    const rules: string[] = [];
    for (const [slot, classes] of slots) {
      const result = await translate(build, classes);
      if (result.unknown.length > 0) {
        missing += result.unknown.length;
        process.stderr.write(`  ${name}/${slot}: NOT A UTILITY: ${result.unknown.join(" ")}\n`);
      }
      if (result.css.trim() === "") continue;
      rules.push(`.${slot} {\n${indent(result.css, "  ")}\n}`);
    }

    const body = indent(rules.join("\n\n"), "    ");
    const sheet =
      `/* ${slots.size} classes from shadcn/ui's registry/styles/${file}.\n` +
      ` * Generated by tools/styles.ts. Do not edit. */\n` +
      `@layer ${LAYER} {\n  .style-${name} {\n${body}\n  }\n}\n`;

    writeFileSync(join(into, `${name}.css`), sheet);
    process.stdout.write(
      `${name}: ${String(slots.size)} classes, ${(sheet.length / 1024).toFixed(1)} KB\n`,
    );
  }

  if (missing > 0) process.exitCode = 1;
}

// Only when RUN. `parseStyle` is the half worth testing, and importing it must
// not translate three thousand classes first.
if (import.meta.main) await main();
