/**
 * `src/theme/themes.ts`, from a shadcn/ui checkout.
 *
 * The colour themes are shadcn's, verbatim, because the point of this package
 * is that a barq application looks like a shadcn one. Transcribing them by
 * hand would drift on the first upstream change; this reads
 * `apps/v4/registry/themes.ts` and writes the data module the package ships.
 *
 * ```
 * bun run tools/themes.ts ../../../vendor/ui
 * ```
 *
 * The file it reads declares `THEMES: RegistryItem[]` and imports that type
 * from `shadcn/schema`, which is not installed here — so the import line is
 * replaced before the module is evaluated.
 */

import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

interface UpstreamTheme {
  readonly name: string;
  readonly title: string;
  readonly cssVars: {
    readonly light: Record<string, string>;
    readonly dark: Record<string, string>;
  };
}

/** A base theme declares every token; an accent overlays a handful onto one. */
const BASE_TOKEN_COUNT = 20;

function quote(value: string): string {
  return JSON.stringify(value);
}

function tokens(map: Record<string, string>, indent: string): string {
  const lines = Object.entries(map).map(
    ([token, value]) => `${indent}  ${quote(token)}: ${quote(value)},`,
  );
  return `{\n${lines.join("\n")}\n${indent}}`;
}

function theme(item: UpstreamTheme, kind: "base" | "accent"): string {
  return [
    `  {`,
    `    name: ${quote(item.name)},`,
    `    title: ${quote(item.title)},`,
    `    kind: ${quote(kind)},`,
    `    light: ${tokens(item.cssVars.light, "    ")},`,
    `    dark: ${tokens(item.cssVars.dark, "    ")},`,
    `  },`,
  ].join("\n");
}

async function read(checkout: string): Promise<UpstreamTheme[]> {
  const source = readFileSync(resolve(checkout, "apps/v4/registry/themes.ts"), "utf8");
  const scratch = join(mkdtempSync(join(tmpdir(), "barq-ui-themes-")), "themes.ts");
  writeFileSync(scratch, source.replace(/^import .*$/m, "export type RegistryItem = unknown;"));
  const module_ = (await import(scratch)) as { THEMES: UpstreamTheme[] };
  return module_.THEMES;
}

const HEADER = `/**
 * Every colour theme shadcn/ui ships, as data.
 *
 * GENERATED by \`tools/themes.ts\` from a shadcn/ui checkout. Edit that, not
 * this.
 *
 * Data rather than CSS because an application uses one of these and should pay
 * for one: \`installTheme\` registers the chosen pair of rules, and the CLI's
 * \`init\` writes them into a \`globalCss\` block the compiler folds away. Both
 * read from here.
 *
 * A **base** declares the whole token set. An **accent** overlays a handful
 * onto whichever base is already there, which is why \`primary\` and the chart
 * ramp are all most of them carry.
 */

export interface ThemeTokens {
  readonly [token: string]: string;
}

export interface ThemeDefinition {
  readonly name: string;
  readonly title: string;
  readonly kind: "base" | "accent";
  readonly light: ThemeTokens;
  readonly dark: ThemeTokens;
}
`;

async function main(): Promise<void> {
  const checkout = process.argv[2];
  if (checkout === undefined)
    throw new Error("usage: bun run tools/themes.ts <shadcn-ui-checkout>");

  const upstream = await read(checkout);
  const bases = upstream.filter(
    (item) => Object.keys(item.cssVars.light).length > BASE_TOKEN_COUNT,
  );
  const accents = upstream.filter(
    (item) => Object.keys(item.cssVars.light).length <= BASE_TOKEN_COUNT,
  );

  const out = [
    HEADER,
    `export const BASE_THEMES: readonly ThemeDefinition[] = [`,
    bases.map((item) => theme(item, "base")).join("\n"),
    `];`,
    ``,
    `export const ACCENT_THEMES: readonly ThemeDefinition[] = [`,
    accents.map((item) => theme(item, "accent")).join("\n"),
    `];`,
    ``,
    `export const THEMES: readonly ThemeDefinition[] = [...BASE_THEMES, ...ACCENT_THEMES];`,
    ``,
    `export function findTheme(name: string): ThemeDefinition | undefined {`,
    `  return THEMES.find((entry) => entry.name === name);`,
    `}`,
    ``,
  ].join("\n");

  const target = resolve(import.meta.dir, "../src/theme/themes.ts");
  writeFileSync(target, out);
  process.stdout.write(`${bases.length} bases, ${accents.length} accents -> ${target}\n`);
}

await main();
