/**
 * `@barqjs/ui` — shadcn/ui's components, on `@barqjs/aria` and `@barqjs/css`.
 *
 * GENERATED by `tools/exports.ts` from what `src/ui` contains. Edit that, not
 * this.
 *
 * Importing this installs the scale and the layer order every component's CSS
 * reads. The RESET is a separate import (`@barqjs/ui/theme/reset`) and a colour
 * theme is chosen by you, because neither is a decision a component library
 * gets to make for an application.
 *
 * Every component is an entry point of its own as well as being re-exported
 * here, so `@barqjs/ui/button` and a tree-shaken import from the root cost the
 * same.
 */

import "./theme/base.ts";

export { ui, uiVariants } from "./lib/atoms.ts";
export {
  overlayFamily,
  type OverlayFamily,
  type OverlayKind,
  type OverlayRootProps,
  type OverlayValue,
} from "./lib/overlay.tsx";
export { type UiProps } from "./lib/props.ts";
export { box } from "./lib/shared-box.ts";
export { icon } from "./lib/shared-icon.ts";
export { ringSlot } from "./lib/shared-ring-slot.ts";
export { ring } from "./lib/shared-ring.ts";
export { text } from "./lib/shared-text.ts";
export { when } from "./lib/shared-when.ts";
export { controlProps, uiProps } from "./lib/slot.ts";
export { cn } from "./lib/utils.ts";
export {
  ACCENT_THEMES,
  BASE_THEMES,
  chart,
  findTheme,
  installTheme,
  themeCss,
  type ThemeDefinition,
  THEMES,
  type ThemeSelection,
  type ThemeTokens,
  type TokenName,
  tokens,
} from "./theme/index.ts";
export {
  Accordion,
  AccordionContent,
  type AccordionContentProps,
  AccordionItem,
  type AccordionItemProps,
  type AccordionProps,
  AccordionTrigger,
  type AccordionTriggerProps,
} from "./ui/accordion.tsx";
export {
  AlertDialog,
  AlertDialogAction,
  type AlertDialogActionProps,
  AlertDialogCancel,
  AlertDialogContent,
  type AlertDialogContentProps,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogMedia,
  type AlertDialogProps,
  type AlertDialogSize,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "./ui/alert-dialog.tsx";
export {
  Alert,
  AlertDescription,
  type AlertProps,
  AlertTitle,
  type AlertVariant,
  alertVariants,
} from "./ui/alert.tsx";
export { AspectRatio, type AspectRatioProps } from "./ui/aspect-ratio.tsx";
export {
  Avatar,
  AvatarBadge,
  AvatarFallback,
  AvatarImage,
  type AvatarImageProps,
  type AvatarProps,
  type AvatarSize,
} from "./ui/avatar.tsx";
export { Badge, type BadgeProps, type BadgeVariant, badgeVariants } from "./ui/badge.tsx";
export {
  Breadcrumb,
  BreadcrumbEllipsis,
  BreadcrumbItem,
  BreadcrumbLink,
  type BreadcrumbLinkProps,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
  type BreadcrumbSeparatorProps,
} from "./ui/breadcrumb.tsx";
export {
  ButtonGroup,
  type ButtonGroupOrientation,
  type ButtonGroupProps,
  ButtonGroupSeparator,
  type ButtonGroupSeparatorProps,
  ButtonGroupText,
  buttonGroupVariants,
} from "./ui/button-group.tsx";
export {
  Button,
  type ButtonProps,
  type ButtonSize,
  type ButtonVariant,
  buttonVariants,
} from "./ui/button.tsx";
export {
  Calendar,
  CalendarDay,
  type CalendarDayProps,
  type CalendarProps,
  RangeCalendar,
  type RangeCalendarProps,
} from "./ui/calendar.tsx";
export {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  type CardEdgeProps,
  CardFooter,
  CardHeader,
  CardTitle,
} from "./ui/card.tsx";
export { Checkbox, type CheckboxProps } from "./ui/checkbox.tsx";
export {
  Collapsible,
  CollapsibleContent,
  type CollapsibleContentProps,
  type CollapsibleProps,
  CollapsibleTrigger,
  type CollapsibleTriggerProps,
} from "./ui/collapsible.tsx";
export { Combobox, type ComboboxProps } from "./ui/combobox.tsx";
export {
  Command,
  CommandDialog,
  type CommandDialogProps,
  CommandGroup,
  type CommandGroupProps,
  CommandItem,
  type CommandItemProps,
  type CommandProps,
  CommandSeparator,
  CommandShortcut,
} from "./ui/command.tsx";
export {
  ContextMenu,
  ContextMenuCheckboxItem,
  type ContextMenuCheckboxItemProps,
  ContextMenuContent,
  type ContextMenuContentProps,
  ContextMenuGroup,
  ContextMenuGroupLabel,
  type ContextMenuGroupProps,
  ContextMenuItem,
  type ContextMenuItemProps,
  ContextMenuLabel,
  type ContextMenuLabelProps,
  type ContextMenuProps,
  ContextMenuRadioItem,
  type ContextMenuRadioItemProps,
  ContextMenuSeparator,
  ContextMenuShortcut,
  ContextMenuSub,
  ContextMenuSubContent,
  type ContextMenuSubContentProps,
  type ContextMenuSubProps,
  ContextMenuSubTrigger,
  type ContextMenuSubTriggerProps,
  ContextMenuTrigger,
  type ContextMenuTriggerProps,
} from "./ui/context-menu.tsx";
export {
  Dialog,
  DialogClose,
  type DialogCloseProps,
  DialogContent,
  type DialogContentProps,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  type DialogProps,
  DialogTitle,
  DialogTrigger,
} from "./ui/dialog.tsx";
export {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  type DropdownMenuCheckboxItemProps,
  DropdownMenuContent,
  type DropdownMenuContentProps,
  DropdownMenuGroup,
  DropdownMenuGroupLabel,
  type DropdownMenuGroupProps,
  DropdownMenuItem,
  type DropdownMenuItemProps,
  type DropdownMenuItemVariant,
  DropdownMenuLabel,
  type DropdownMenuLabelProps,
  type DropdownMenuProps,
  DropdownMenuRadioItem,
  type DropdownMenuRadioItemProps,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  type DropdownMenuSubContentProps,
  type DropdownMenuSubProps,
  DropdownMenuSubTrigger,
  type DropdownMenuSubTriggerProps,
  DropdownMenuTrigger,
} from "./ui/dropdown-menu.tsx";
export {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  type EmptyMediaProps,
  type EmptyMediaVariant,
  emptyMediaVariants,
  EmptyTitle,
} from "./ui/empty.tsx";
export {
  Field,
  FieldContent,
  FieldDescription,
  FieldError,
  type FieldErrorProps,
  FieldGroup,
  type FieldGroupProps,
  FieldLabel,
  type FieldLabelProps,
  FieldLegend,
  type FieldLegendProps,
  type FieldLegendVariant,
  fieldLegendVariants,
  type FieldOrientation,
  type FieldProps,
  FieldSeparator,
  type FieldSeparatorProps,
  FieldSet,
  FieldTitle,
  fieldVariants,
} from "./ui/field.tsx";
export {
  HoverCard,
  HoverCardContent,
  type HoverCardContentProps,
  type HoverCardProps,
  HoverCardTrigger,
} from "./ui/hover-card.tsx";
export {
  InputGroup,
  InputGroupAddon,
  type InputGroupAddonProps,
  inputGroupAddonVariants,
  type InputGroupAlign,
  InputGroupButton,
  type InputGroupButtonProps,
  type InputGroupButtonSize,
  inputGroupButtonVariants,
  InputGroupInput,
  type InputGroupInputProps,
  type InputGroupProps,
  InputGroupText,
  InputGroupTextarea,
  type InputGroupTextareaProps,
} from "./ui/input-group.tsx";
export { Input, type InputProps, Textarea, type TextareaProps } from "./ui/input.tsx";
export {
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemFooter,
  ItemGroup,
  ItemHeader,
  ItemMedia,
  type ItemMediaProps,
  type ItemMediaVariant,
  itemMediaVariants,
  type ItemProps,
  ItemSeparator,
  type ItemSeparatorProps,
  type ItemSize,
  ItemTitle,
  type ItemVariant,
  itemVariants,
} from "./ui/item.tsx";
export { Kbd, KbdGroup } from "./ui/kbd.tsx";
export { Label, type LabelProps } from "./ui/label.tsx";
export {
  Menubar,
  MenubarCheckboxItem,
  type MenubarCheckboxItemProps,
  MenubarContent,
  type MenubarContentProps,
  MenubarGroup,
  MenubarGroupLabel,
  type MenubarGroupProps,
  MenubarItem,
  type MenubarItemProps,
  MenubarLabel,
  type MenubarLabelProps,
  MenubarMenu,
  type MenubarMenuProps,
  type MenubarProps,
  MenubarRadioItem,
  type MenubarRadioItemProps,
  MenubarSeparator,
  MenubarShortcut,
  MenubarSub,
  MenubarSubContent,
  type MenubarSubContentProps,
  type MenubarSubProps,
  MenubarSubTrigger,
  type MenubarSubTriggerProps,
  MenubarTrigger,
  type MenubarTriggerProps,
} from "./ui/menubar.tsx";
export { NativeSelect, type NativeSelectProps } from "./ui/native-select.tsx";
export {
  Pagination,
  PaginationContent,
  type PaginationEdgeProps,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  type PaginationLinkProps,
  PaginationNext,
  PaginationPrevious,
} from "./ui/pagination.tsx";
export {
  Popover,
  PopoverContent,
  type PopoverContentProps,
  PopoverDescription,
  PopoverHeader,
  type PopoverProps,
  PopoverTitle,
  PopoverTrigger,
} from "./ui/popover.tsx";
export { Progress, type ProgressProps } from "./ui/progress.tsx";
export {
  RadioGroup,
  RadioGroupItem,
  type RadioGroupItemProps,
  type RadioGroupProps,
} from "./ui/radio-group.tsx";
export { ScrollArea, type ScrollAreaProps } from "./ui/scroll-area.tsx";
export {
  Select,
  SelectItem,
  type SelectItemProps,
  SelectLabel,
  type SelectProps,
  SelectSeparator,
  type SelectSize,
  SelectValue,
} from "./ui/select.tsx";
export { Separator, type SeparatorProps } from "./ui/separator.tsx";
export {
  Sheet,
  SheetClose,
  type SheetCloseProps,
  SheetContent,
  type SheetContentProps,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  type SheetProps,
  type SheetSide,
  SheetTitle,
  SheetTrigger,
  sheetVariants,
} from "./ui/sheet.tsx";
export { Skeleton } from "./ui/skeleton.tsx";
export { Slider, type SliderProps } from "./ui/slider.tsx";
export { Spinner, type SpinnerProps } from "./ui/spinner.tsx";
export { srOnly } from "./ui/sr-only.ts";
export { Switch, type SwitchProps, type SwitchSize } from "./ui/switch.tsx";
export {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  type TableCellProps,
  TableFooter,
  TableHead,
  TableHeader,
  type TableHeadProps,
  TableRow,
  type TableRowProps,
} from "./ui/table.tsx";
export {
  Tabs,
  TabsContent,
  type TabsContentProps,
  TabsList,
  type TabsListProps,
  type TabsListVariant,
  tabsListVariants,
  type TabsProps,
  TabsTrigger,
  type TabsTriggerProps,
} from "./ui/tabs.tsx";
export {
  ToggleGroup,
  ToggleGroupItem,
  type ToggleGroupItemProps,
  type ToggleGroupProps,
  type ToggleGroupType,
} from "./ui/toggle-group.tsx";
export {
  Toggle,
  type ToggleProps,
  type ToggleSize,
  type ToggleVariant,
  toggleVariants,
} from "./ui/toggle.tsx";
export {
  Tooltip,
  TooltipContent,
  type TooltipContentProps,
  type TooltipProps,
} from "./ui/tooltip.tsx";
