#!/usr/bin/env node
/**
 * `bun create barq my-app` / `npm create barq@latest my-app`.
 *
 * NO DEPENDENCIES. A `create-*` package is downloaded before the project it
 * scaffolds exists, so every dependency is latency a person pays before seeing
 * anything — the argument parsing and the two prompts here are smaller than the
 * libraries that would do them.
 *
 * It scaffolds a project and stops. Route generators (`barq add route /posts/$id`)
 * are the obvious next thing and are deliberately not here: the route tree is
 * already generated by the Vite plugin, so the CLI's only job today is the one
 * a person cannot do by copying a directory.
 */

import { basename, resolve } from "node:path";
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";

import { isEmpty, isValidPackageName, scaffold, toValidPackageName } from "./scaffold.ts";
import { DEFAULT_TEMPLATE, TEMPLATES, findTemplate } from "./templates.ts";

const HELP = `\
Usage: create-barq [directory] [options]

Create a barq project.

Options:
  -t, --template NAME   ${TEMPLATES.map((t) => t.name).join(" | ")}
      --overwrite       empty the directory first
  -h, --help            show this

Templates:
${TEMPLATES.map((t) => `  ${t.name.padEnd(12)}${t.description}`).join("\n")}
`;

interface Args {
  readonly directory?: string;
  readonly template?: string;
  readonly overwrite: boolean;
  readonly help: boolean;
}

function parse(argv: readonly string[]): Args {
  let directory: string | undefined;
  let template: string | undefined;
  let overwrite = false;
  let help = false;

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i] ?? "";
    if (arg === "-h" || arg === "--help") help = true;
    else if (arg === "--overwrite") overwrite = true;
    else if (arg === "-t" || arg === "--template") template = argv[++i];
    else if (arg.startsWith("--template=")) template = arg.slice("--template=".length);
    // An unknown flag is not a directory name. Silently scaffolding into
    // `--tempalte` is the typo this refuses.
    else if (arg.startsWith("-")) throw new Error(`unknown option ${arg}`);
    else directory ??= arg;
  }

  return { directory, template, overwrite, help };
}

/** What ran us, for the "now run" lines. `npm_config_user_agent` is set by all of them. */
function packageManager(): string {
  const agent = process.env.npm_config_user_agent;
  const name = agent?.split(" ")[0]?.split("/")[0];
  return name === undefined || name === "" ? "npm" : name;
}

async function main(): Promise<void> {
  const args = parse(process.argv.slice(2));
  if (args.help) {
    stdout.write(HELP);
    return;
  }

  // Prompting needs somewhere to prompt. Piped into a script, the flags are the
  // whole interface and a missing one is an error rather than a hang.
  const rl = stdin.isTTY ? createInterface({ input: stdin, output: stdout }) : null;
  const ask = async (question: string, fallback: string): Promise<string> => {
    if (rl === null) return fallback;
    const answer = (await rl.question(`${question} (${fallback}) `)).trim();
    return answer === "" ? fallback : answer;
  };

  try {
    const directory = args.directory ?? (await ask("Project directory:", "barq-project"));
    const target = resolve(process.cwd(), directory);

    const name = args.template ?? (await askTemplate(ask));
    const template = findTemplate(name);
    if (template === undefined) {
      throw new Error(
        `no template named "${name}". Try one of: ${TEMPLATES.map((t) => t.name).join(", ")}`,
      );
    }

    let overwrite = args.overwrite;
    if (!overwrite && !isEmpty(target)) {
      const answer = await ask(`${directory} is not empty. Empty it?`, "no");
      overwrite = answer.toLowerCase().startsWith("y");
      if (!overwrite) throw new Error(`${directory} is not empty`);
    }

    const suggested = toValidPackageName(basename(target));
    const packageName = isValidPackageName(suggested) ? suggested : "barq-project";

    scaffold({ template: template.name, target, packageName, overwrite });

    const pm = packageManager();
    const install = pm === "npm" ? "npm install" : `${pm} install`;
    const dev = pm === "npm" ? "npm run dev" : `${pm} run dev`;
    stdout.write(
      `\nScaffolded ${template.title} in ${directory}.\n\n  cd ${directory}\n  ${install}\n  ${dev}\n\n`,
    );
  } finally {
    rl?.close();
  }
}

async function askTemplate(
  ask: (question: string, fallback: string) => Promise<string>,
): Promise<string> {
  stdout.write("\nTemplates:\n");
  for (const template of TEMPLATES) {
    stdout.write(`  ${template.name.padEnd(12)}${template.description}\n`);
  }
  return ask("\nTemplate:", DEFAULT_TEMPLATE);
}

main().catch((error: unknown) => {
  stdout.write(`\n${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
