/**
 * The scale every component's CSS reads.
 *
 * GENERATED by `tools/base.ts`. Edit that, not this.
 *
 * Three blocks: the scale itself, which a theme may override; the
 * `@property` declarations behind `box-shadow` composition, which have to
 * be at the top level for a ring and a shadow on one element to add
 * rather than replace; and the keyframes `animate-spin` and
 * `animate-pulse` reference.
 *
 * The colour tokens are NOT here. Those are a theme, and `installTheme`
 * or the CLI's `init` puts one on the page.
 */

import { globalCss } from "@barqjs/css";

import "./layers.ts";

globalCss`
@layer barq.base {
  :root, :host {
    --font-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    --font-mono: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
    --color-black: #000;
    --color-white: #fff;
    --spacing: 0.25rem;
    --container-xs: 20rem;
    --container-sm: 24rem;
    --container-lg: 32rem;
    --text-xs: 0.75rem;
    --text-xs--line-height: calc(1 / 0.75);
    --text-sm: 0.875rem;
    --text-sm--line-height: calc(1.25 / 0.875);
    --text-base: 1rem;
    --text-base--line-height: calc(1.5 / 1);
    --text-lg: 1.125rem;
    --text-lg--line-height: calc(1.75 / 1.125);
    --font-weight-normal: 400;
    --font-weight-medium: 500;
    --font-weight-semibold: 600;
    --tracking-tight: -0.025em;
    --tracking-widest: 0.1em;
    --leading-tight: 1.25;
    --leading-snug: 1.375;
    --leading-normal: 1.5;
    --leading-relaxed: 1.625;
    --radius-xs: 0.125rem;
    --ease-in-out: cubic-bezier(0.4, 0, 0.2, 1);
    --animate-spin: spin 1s linear infinite;
    --animate-pulse: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
    --aspect-video: 16 / 9;
    --default-transition-duration: 150ms;
    --default-transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    --default-font-family: var(--font-sans);
    --default-mono-font-family: var(--font-mono);
    --color-border: var(--border);
  }
}
`;

globalCss`
@property --ui-animation-delay {
  syntax: "*";
  inherits: false;
  initial-value: 0s;
}
@property --ui-animation-direction {
  syntax: "*";
  inherits: false;
  initial-value: normal;
}
@property --ui-animation-duration {
  syntax: "*";
  inherits: false;
}
@property --ui-animation-fill-mode {
  syntax: "*";
  inherits: false;
  initial-value: none;
}
@property --ui-animation-iteration-count {
  syntax: "*";
  inherits: false;
  initial-value: 1;
}
@property --ui-enter-blur {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}
@property --ui-enter-opacity {
  syntax: "*";
  inherits: false;
  initial-value: 1;
}
@property --ui-enter-rotate {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}
@property --ui-enter-scale {
  syntax: "*";
  inherits: false;
  initial-value: 1;
}
@property --ui-enter-translate-x {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}
@property --ui-enter-translate-y {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}
@property --ui-exit-blur {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}
@property --ui-exit-opacity {
  syntax: "*";
  inherits: false;
  initial-value: 1;
}
@property --ui-exit-rotate {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}
@property --ui-exit-scale {
  syntax: "*";
  inherits: false;
  initial-value: 1;
}
@property --ui-exit-translate-x {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}
@property --ui-exit-translate-y {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}
@property --ui-translate-x {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}
@property --ui-translate-y {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}
@property --ui-translate-z {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}
@property --ui-scroll-snap-strictness {
  syntax: "*";
  inherits: false;
  initial-value: proximity;
}
@property --ui-space-x-reverse {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}
@property --ui-border-style {
  syntax: "*";
  inherits: false;
  initial-value: solid;
}
@property --ui-leading {
  syntax: "*";
  inherits: false;
}
@property --ui-font-weight {
  syntax: "*";
  inherits: false;
}
@property --ui-tracking {
  syntax: "*";
  inherits: false;
}
@property --ui-ordinal {
  syntax: "*";
  inherits: false;
}
@property --ui-slashed-zero {
  syntax: "*";
  inherits: false;
}
@property --ui-numeric-figure {
  syntax: "*";
  inherits: false;
}
@property --ui-numeric-spacing {
  syntax: "*";
  inherits: false;
}
@property --ui-numeric-fraction {
  syntax: "*";
  inherits: false;
}
@property --ui-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}
@property --ui-shadow-color {
  syntax: "*";
  inherits: false;
}
@property --ui-shadow-alpha {
  syntax: "<percentage>";
  inherits: false;
  initial-value: 100%;
}
@property --ui-inset-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}
@property --ui-inset-shadow-color {
  syntax: "*";
  inherits: false;
}
@property --ui-inset-shadow-alpha {
  syntax: "<percentage>";
  inherits: false;
  initial-value: 100%;
}
@property --ui-ring-color {
  syntax: "*";
  inherits: false;
}
@property --ui-ring-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}
@property --ui-inset-ring-color {
  syntax: "*";
  inherits: false;
}
@property --ui-inset-ring-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}
@property --ui-ring-inset {
  syntax: "*";
  inherits: false;
}
@property --ui-ring-offset-width {
  syntax: "<length>";
  inherits: false;
  initial-value: 0px;
}
@property --ui-ring-offset-color {
  syntax: "*";
  inherits: false;
  initial-value: #fff;
}
@property --ui-ring-offset-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}
@property --ui-outline-style {
  syntax: "*";
  inherits: false;
  initial-value: solid;
}
@property --ui-duration {
  syntax: "*";
  inherits: false;
}
@property --ui-ease {
  syntax: "*";
  inherits: false;
}
@property --ui-content {
  syntax: "*";
  initial-value: "";
  inherits: false;
}
@property --ui-scale-x {
  syntax: "*";
  inherits: false;
  initial-value: 1;
}
@property --ui-scale-y {
  syntax: "*";
  inherits: false;
  initial-value: 1;
}
@property --ui-scale-z {
  syntax: "*";
  inherits: false;
  initial-value: 1;
}
`;

globalCss`
@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
@keyframes pulse {
  50% {
    opacity: 0.5;
  }
}
@keyframes enter {
  from {
    opacity: var(--ui-enter-opacity,1);
    transform: translate3d(var(--ui-enter-translate-x,0),var(--ui-enter-translate-y,0),0)scale3d(var(--ui-enter-scale,1),var(--ui-enter-scale,1),var(--ui-enter-scale,1))rotate(var(--ui-enter-rotate,0));
    filter: blur(var(--ui-enter-blur,0));
  }
}
@keyframes exit {
  to {
    opacity: var(--ui-exit-opacity,1);
    transform: translate3d(var(--ui-exit-translate-x,0),var(--ui-exit-translate-y,0),0)scale3d(var(--ui-exit-scale,1),var(--ui-exit-scale,1),var(--ui-exit-scale,1))rotate(var(--ui-exit-rotate,0));
    filter: blur(var(--ui-exit-blur,0));
  }
}
@keyframes caret-blink {
  0%,70%,100% {
    opacity: 1;
  }
  20%,50% {
    opacity: 0;
  }
}
`;
