// Generated by @barqjs/router. Do not edit.
declare module "virtual:barq-routes" {
  type StandardOut<R> = R extends { value: infer S } ? S : never;
  type ValidatedBy<V> = V extends { "~standard": { validate: (value: never) => infer R } }
    ? StandardOut<Awaited<R>>
    : V extends { parse: (input: never) => infer S }
      ? S
      : V extends (input: never) => infer S
        ? S
        : never;
  type SearchOf<M> = M extends { validateSearch: infer V } ? ValidatedBy<V> : Record<string, unknown>;
  type DataOf<M> = M extends { loader: infer L } ? (L extends (...args: never) => infer R ? Awaited<R> : never) : undefined;

  export interface RouteMap {
    "/about": { path: "/about"; params: {  } };
    "/async": { path: "/async"; params: {  } };
    "/components": { path: "/components"; params: {  } };
    "/css": { path: "/css"; params: {  } };
    "/hooks": { path: "/hooks"; params: {  } };
    "/": { path: "/"; params: {  } };
    "/jsx-types": { path: "/jsx-types"; params: {  } };
    "/query": { path: "/query"; params: {  } };
    "/routing": { path: "/routing"; params: {  } };
    "/signals": { path: "/signals"; params: {  } };
    "/store": { path: "/store"; params: {  } };
  }

  export interface RouteData {
    "__root__": { search: SearchOf<typeof import("../src/routes/route.tsx")>; data: DataOf<typeof import("../src/routes/route.tsx")> };
    "/about": { search: SearchOf<typeof import("../src/routes/about.tsx")>; data: DataOf<typeof import("../src/routes/about.tsx")> };
    "/async": { search: SearchOf<typeof import("../src/routes/async.tsx")>; data: DataOf<typeof import("../src/routes/async.tsx")> };
    "/components": { search: SearchOf<typeof import("../src/routes/components.tsx")>; data: DataOf<typeof import("../src/routes/components.tsx")> };
    "/css": { search: SearchOf<typeof import("../src/routes/css.tsx")>; data: DataOf<typeof import("../src/routes/css.tsx")> };
    "/hooks": { search: SearchOf<typeof import("../src/routes/hooks.tsx")>; data: DataOf<typeof import("../src/routes/hooks.tsx")> };
    "/": { search: SearchOf<typeof import("../src/routes/index.tsx")>; data: DataOf<typeof import("../src/routes/index.tsx")> };
    "/jsx-types": { search: SearchOf<typeof import("../src/routes/jsx-types.tsx")>; data: DataOf<typeof import("../src/routes/jsx-types.tsx")> };
    "/query": { search: SearchOf<typeof import("../src/routes/query.tsx")>; data: DataOf<typeof import("../src/routes/query.tsx")> };
    "/routing": { search: SearchOf<typeof import("../src/routes/routing.tsx")>; data: DataOf<typeof import("../src/routes/routing.tsx")> };
    "/signals": { search: SearchOf<typeof import("../src/routes/signals.tsx")>; data: DataOf<typeof import("../src/routes/signals.tsx")> };
    "/store": { search: SearchOf<typeof import("../src/routes/store.tsx")>; data: DataOf<typeof import("../src/routes/store.tsx")> };
  }

  export type RouteId = keyof RouteMap & string;
  export type RoutePath = RouteMap[RouteId]["path"];
  export type SearchFor<Id extends keyof RouteData> = RouteData[Id]["search"];
  export type DataFor<Id extends keyof RouteData> = RouteData[Id]["data"];
  export const routes: import("@barqjs/router").AnyRouteDefinition[];
  export default routes;
}
