// Generated by @barqjs/router. Do not edit.
//
// The route table and the route types, in one module the application imports by
// PATH — TanStack Start's `routeTree.gen.ts` arrangement, and for their reason:
// a generated file that a project can open, typecheck and read is worth more
// than a virtual specifier only the bundler can resolve.
//
// Every route module is imported STATICALLY, so `...Route.options` carries the
// whole option set. The components are split out of the route module by the
// compiler, not by this table.

import { Outlet } from "@barqjs/router";
import type { AnyRouteDefinition } from "@barqjs/router";

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as AboutRoute } from "./routes/about";
import { Route as AdminRoute } from "./routes/admin";
import { Route as AsyncRoute } from "./routes/async";
import { Route as ComponentsRoute } from "./routes/components";
import { Route as ControlRoute } from "./routes/control";
import { Route as CssRoute } from "./routes/css";
import { Route as HooksRoute } from "./routes/hooks";
import { Route as JsxTypesRoute } from "./routes/jsx-types";
import { Route as LinksRoute } from "./routes/links";
import { Route as QueryRoute } from "./routes/query";
import { Route as RoutingRoute } from "./routes/routing";
import { Route as ShopRoute } from "./routes/shop";
import { Route as ShopIndexRoute } from "./routes/shop.index";
import { Route as SignalsRoute } from "./routes/signals";
import { Route as StoreRoute } from "./routes/store";
import { Route as ApiHealthRoute } from "./routes/api/health";
import { Route as ReportChar123nameChar125DotcsvRoute } from "./routes/report.{$name}[.]csv";
import { Route as DocsChar123VersionChar125GuideRoute } from "./routes/docs.{-$version}.guide";

/**
 * The table, exactly the shape `createRouter` and `createPageHandler` take.
 *
 * `...Route.options` FIRST, so the generator's `id`, `path` and `src` win over
 * anything a route module happens to spell for itself — the filename is what
 * decides those, and a route that disagrees is already refused by the id check.
 */
export const routeTree: AnyRouteDefinition[] = [
  { ...rootRoute.options, id: "__root__", path: "/", src: "/src/routes/__root.tsx", children: [
    { ...IndexRoute.options, id: "/", path: "", src: "/src/routes/index.tsx", prerender: true },
    { ...AboutRoute.options, id: "/about", path: "about", src: "/src/routes/about.tsx", prerender: true },
    { ...AdminRoute.options, id: "/admin", path: "admin", src: "/src/routes/admin.tsx" },
    { ...AsyncRoute.options, id: "/async", path: "async", src: "/src/routes/async.tsx" },
    { ...ComponentsRoute.options, id: "/components", path: "components", src: "/src/routes/components.tsx" },
    { ...ControlRoute.options, id: "/control", path: "control", src: "/src/routes/control.tsx" },
    { ...CssRoute.options, id: "/css", path: "css", src: "/src/routes/css.tsx" },
    { ...HooksRoute.options, id: "/hooks", path: "hooks", src: "/src/routes/hooks.tsx", ssr: false },
    { ...JsxTypesRoute.options, id: "/jsx-types", path: "jsx-types", src: "/src/routes/jsx-types.tsx" },
    { ...LinksRoute.options, id: "/links", path: "links", src: "/src/routes/links.tsx" },
    { ...QueryRoute.options, id: "/query", path: "query", src: "/src/routes/query.tsx", ssr: "data-only" },
    { ...RoutingRoute.options, id: "/routing", path: "routing", src: "/src/routes/routing.tsx", ssr: false },
    { ...ShopRoute.options, id: "/shop", path: "shop", src: "/src/routes/shop.tsx", children: [
      { ...ShopIndexRoute.options, id: "/shop/", path: "", src: "/src/routes/shop.index.tsx" }
    ] },
    { ...SignalsRoute.options, id: "/signals", path: "signals", src: "/src/routes/signals.tsx" },
    { ...StoreRoute.options, id: "/store", path: "store", src: "/src/routes/store.tsx" },
    { ...ApiHealthRoute.options, id: "/api/health", path: "api/health", src: "/src/routes/api/health.ts", component: Outlet as never },
    { ...ReportChar123nameChar125DotcsvRoute.options, id: "/report/{$name}.csv", path: "report/{$name}.csv", src: "/src/routes/report.{$name}[.]csv.tsx" },
    { ...DocsChar123VersionChar125GuideRoute.options, id: "/docs/{-$version}/guide", path: "docs/{-$version}/guide", src: "/src/routes/docs.{-$version}.guide.tsx" }
  ] }
];

export default routeTree;

export interface FileRoutesById {
  "__root__": typeof rootRoute;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/admin": typeof AdminRoute;
  "/async": typeof AsyncRoute;
  "/components": typeof ComponentsRoute;
  "/control": typeof ControlRoute;
  "/css": typeof CssRoute;
  "/hooks": typeof HooksRoute;
  "/jsx-types": typeof JsxTypesRoute;
  "/links": typeof LinksRoute;
  "/query": typeof QueryRoute;
  "/routing": typeof RoutingRoute;
  "/shop": typeof ShopRoute;
  "/shop/": typeof ShopIndexRoute;
  "/signals": typeof SignalsRoute;
  "/store": typeof StoreRoute;
  "/api/health": typeof ApiHealthRoute;
  "/report/{$name}.csv": typeof ReportChar123nameChar125DotcsvRoute;
  "/docs/{-$version}/guide": typeof DocsChar123VersionChar125GuideRoute;
}

export interface FileRouteTypes {
  /** Every route id, layouts included — what `useMatch` and `Link`'s `to` address. */
  id: "__root__" | "/" | "/about" | "/admin" | "/async" | "/components" | "/control" | "/css" | "/hooks" | "/jsx-types" | "/links" | "/query" | "/routing" | "/shop" | "/shop/" | "/signals" | "/store" | "/api/health" | "/report/{$name}.csv" | "/docs/{-$version}/guide";
  /** Every ADDRESSABLE pattern — a leaf, since a layout is reached through one. */
  fullPaths: "/" | "/about" | "/admin" | "/async" | "/components" | "/control" | "/css" | "/hooks" | "/jsx-types" | "/links" | "/query" | "/routing" | "/shop" | "/signals" | "/store" | "/api/health" | "/report/{$name}.csv" | "/docs/{-$version}/guide";
  fileRoutesById: FileRoutesById;
}

declare module "@barqjs/router" {
  interface Register {
    routeTree: FileRouteTypes;
  }
}
